### ISSUE TITLE
setState() called after dispose()

### ISSUE THREAD

**Issue by francisnnumbi** [jinosh05/fancy_bottom_navigation_2#1]
I have noticed that when you route off the widget and this is distroyed, not appearing in the widget tree, the delay in calling `setState()` generate an exception as the state of the component is null.

The suggested solution is to check the `mounted` property of the object before calling `setState()` to ensure the object is still in the tree.

**Comment by jinosh05** [comment]
Thanks for the issue and PR . I have just updated the code
